#!/bin/bash

git stash -q --keep-index

./gradlew build

if [ $? -ne 0 ]; then
    echo "Build failed. Fix the issues and try committing again."
    git stash pop -q
    exit 1
fi

git stash pop -q

exit 0